// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: duha.sql

package db

import (
	"context"
	"database/sql"
)

const checkDuhaExists = `-- name: CheckDuhaExists :one
SELECT EXISTS (
    SELECT 1
    FROM duha
    WHERE user_id = $1
      AND DATE(created_at) = CURRENT_DATE
)
`

func (q *Queries) CheckDuhaExists(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkDuhaExists, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getDuhaData = `-- name: GetDuhaData :many
select created_at from duha where user_id = $1 and done = true
`

func (q *Queries) GetDuhaData(ctx context.Context, userID int64) ([]sql.NullTime, error) {
	rows, err := q.db.QueryContext(ctx, getDuhaData, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullTime
	for rows.Next() {
		var created_at sql.NullTime
		if err := rows.Scan(&created_at); err != nil {
			return nil, err
		}
		items = append(items, created_at)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDuhaDone = `-- name: UpsertDuhaDone :exec
INSERT INTO duha (user_id, done)
VALUES ($1, TRUE)
`

func (q *Queries) UpsertDuhaDone(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, upsertDuhaDone, userID)
	return err
}
