// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: fajr.sql

package db

import (
	"context"
	"database/sql"
)

const checkFajrExists = `-- name: CheckFajrExists :one
SELECT EXISTS (
    SELECT 1
    FROM fajr
    WHERE user_id = $1
      AND DATE(created_at) = CURRENT_DATE
)
`

func (q *Queries) CheckFajrExists(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkFajrExists, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getFajrData = `-- name: GetFajrData :many
select created_at from fajr where user_id = $1 and done = true
`

func (q *Queries) GetFajrData(ctx context.Context, userID int64) ([]sql.NullTime, error) {
	rows, err := q.db.QueryContext(ctx, getFajrData, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullTime
	for rows.Next() {
		var created_at sql.NullTime
		if err := rows.Scan(&created_at); err != nil {
			return nil, err
		}
		items = append(items, created_at)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFajrDone = `-- name: UpsertFajrDone :exec
INSERT INTO fajr (user_id, done)
VALUES ($1, TRUE)
`

func (q *Queries) UpsertFajrDone(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, upsertFajrDone, userID)
	return err
}
