// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Duha struct {
	ID        int32        `json:"id"`
	UserID    int64        `json:"user_id"`
	Done      sql.NullBool `json:"done"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Fajr struct {
	ID        int32        `json:"id"`
	UserID    int64        `json:"user_id"`
	Done      sql.NullBool `json:"done"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Tafsir struct {
	ID        int32        `json:"id"`
	UserID    int64        `json:"user_id"`
	Done      sql.NullBool `json:"done"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	ID        int32        `json:"id"`
	UserID    int64        `json:"user_id"`
	Username  string       `json:"username"`
	CreatedAt sql.NullTime `json:"created_at"`
}
